### ISSUE TITLE
Blank white screen when opening Telescope

### ISSUE THREAD

**Issue by GeckoEidechse** [AsteroidOS/telescope#48]
When opening *Telescope*, all I get is a blank white screen.
I tried closing and re-opening the app, restarting the phone, opening the application with and without manually connecting to my watch first, but all without success.
I also tried switching Ubuntu touch from the Stable channel to Development, again without success in getting anything other than a white screen when opening *Telescope*.

Any ideas on how I could debug what's causing this?

***

* **Device:** Pinephone UBports Community Edition
* **OS:** Ubuntu 16.04
* **OS build number:** 2020-06-30
* **UBport Image part:** 20200630-28374
* **App version:** 0.0.5 installed [via OpenStore](https://open-store.io/app/telescope.asteroidos)

**Comment by StefWe** [comment]
The problem is known and will be fixed in version 0.6 which will be in the open-store soon. If you don't want to wait that long, just drop by in our matrix chat #UBports_AsteroidOS:matrix.org where you can download trial versions

**Comment by GeckoEidechse** [comment]
Using the newest binary mentioned in the matrix channel works. There is no blank white screen issue and I can communicate with the watch :D

I'll close this issue as soon as `0.0.6` is officially released on the [OpenStore](https://open-store.io/app/telescope.asteroidos).

**Comment by StefWe** [comment]
> 
> 
> Using the newest binary mentioned in the matrix channel works. There is no blank white screen issue and I can communicate with the watch :D

That's great news. Have fun with telescope

> 
> I'll close this issue as soon as `0.0.6` is officially released on the [OpenStore](https://open-store.io/app/telescope.asteroidos).

Yeah, that's fine.

**Comment by GeckoEidechse** [comment]
Fixed with `0.0.6`.
