### ISSUE TITLE
Doesn't recognise Moto 360

### ISSUE THREAD

**Issue by jes** [AsteroidOS/telescope#51]
I connected to my device "smelt" using the Bluetooth settings under "System Settings", but even after I restart Telescope I just get this error:

> No smartwatches configured yet. Please connect your smartwatch using System Settings.

So I assume the app does not recognise the watch called "smelt".

It shows up under the Bluetooth settings as "Type = Other".

The phone is a OnePlus One.

**Comment by MagneFire** [comment]
I had a similar issue. In my case rebooting the phone solved the problem. (Paired in settings, still error in app)

My phone is the Xiaomi Mi 3. So not an official build. So it may also be possible that your phone is the problem?
Buto maybe @StefWe knows more about this issue.

**Comment by StefWe** [comment]
When the watch is first paired with the phone, it seems to be "blocked" by the system.
As @MagneFire says, a rebooting the device has also helped me.

I haven't looked for where the error came from yet.

**Comment by jes** [comment]
Thanks! Rebooting the phone has allowed it to show up in the Telescope app!
