### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [AsteroidOS/telescope#61]
https://hosted.weblate.org/projects/asteroidos/telescope/#information is licensed GPLv3-only,
whereas everything else is -or-later.

It can be changed (to GPLv3+) in
https://hosted.weblate.org/settings/asteroidos/telescope
by @FlorentRevest @MagneFire or @jrtberlin

**Comment by MagneFire** [comment]
Thanks for raising this issue!
I've adjusted the license to `GNU General Public License v3.0 or later`.
